FROM node:16-alpine AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY .eslintrc.json ./eslintrc.json
COPY next-env.d.ts ./next-env.d.ts
COPY next.config.js ./next.config.js
COPY postcss.config.js ./postcss.config.js
COPY tailwind.config.js ./tailwind.config.js
COPY tsconfig.json ./tsconfig.json

EXPOSE 3000

CMD ["npm","run","dev"]